### ISSUE TITLE
Href sanitization throwing on server 

### ISSUE THREAD

**Issue by gdub22** [bustlelabs/mobiledoc-dom-renderer#52]
Need to investigate further and follow up.

Updating to 0.6.0+ we saw crashes during server side rendering:
"Mobiledoc DOM Renderer is unable to sanitize href tags in this environment."

We don't shim the `document` globally for node.  We only create a local document variable because it only needs be accessed within our renderer and mobiledoc passes that `dom` param throughout its methods.

**Comment by bantic** [comment]
@gdub22 thanks for reporting — is this running in Fastboot? If so, it is likely related to https://github.com/bustlelabs/ember-mobiledoc-dom-renderer/issues/38.

The environment-detection code in mobiledoc-dom-renderer is: (from `utils/dom.js`):
```
export const isNode = typeof window === 'undefined' && (typeof module === 'object' && typeof module.require === 'function');
export const hasDOM = typeof document === 'object';
```
If both `isNode` and `hasDOM` are false, the renderer will give up on trying to sanitize href and throw ([here](https://github.com/bustlelabs/mobiledoc-dom-renderer/blob/master/lib/utils/sanitization-utils.js#L30)).

This happens when running in Fastboot, so that may be what's happening for you. Or it could be another environment where some combo of `window`,`module` and `module.require` is shimmed, and the `isNode` constant is set incorrectly.
 
ember-mobiledoc-dom-renderer will (soon) pass its a custom markupElementRenderer when it's in a fastboot environment where mobiledoc-dom-renderer would otherwise throw on link sanitization (see https://github.com/bustlelabs/ember-mobiledoc-dom-renderer/pull/42).

If that doesn't address your problem I would think it may be worthwhile to make mobiledoc-dom-renderer use a fallback url protocol parser, something so that it doesn't throw.  I can add that in if the above PR doesn't address this issue.

**Comment by gdub22** [comment]
It's not running in or related to fastboot.
It also worked fine on a local node server.  Saw this seemingly randomly happening on lambda.
Verified that isNode and hasDOM checks are correct in lambda.

**Comment by gdub22** [comment]
https://github.com/bustlelabs/mobiledoc-dom-renderer/pull/53
